### ISSUE TITLE
Unable to add module. Errors out

### ISSUE THREAD

**Issue by id-ic** [mathewmeconry/MMM-HomeAssistant-Touch#3]
I'm having troubles adding the module in my docker container MM.  I'd like to control lights and groups of lights from my wall mounted tablet and I have a very basic config working right now for an other module. 

when I add the below configuration

```
{
    module: "MMM-HomeAssistant-Touch",
    position: "middle",
    config: {
      host: "http://192.168.1.24",
      port: 8123,
      token: "asdf",
      ignoreCert: false,
      entities: [
        "light.basement_light_1",
        "light.master_bedroom_light",
      ]
    }
  },
```

This is the docker logs

```
[19.09.2021 13:04.18.198] [LOG]   Starting MagicMirror: v2.15.0,
[19.09.2021 13:04.18.201] [LOG]   Loading config ...,
[19.09.2021 13:04.18.203] [LOG]   Loading module helpers ...,
[19.09.2021 13:04.18.205] [LOG]   No helper found for module: clock.,
[19.09.2021 13:04.18.378] [LOG]   Initializing new module helper ...,
[19.09.2021 13:04.18.379] [LOG]   Module helper loaded: MMM-CalendarWeek,
[19.09.2021 13:04.18.381] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'homeassistant',
Require stack:,
- /opt/magic_mirror/modules/MMM-HomeAssistant-Touch/node_helper.js,
- /opt/magic_mirror/js/app.js,
- /opt/magic_mirror/serveronly/index.js,
[19.09.2021 13:04.18.382] [LOG]   Loading module helpers ...,
[19.09.2021 13:04.18.382] [LOG]   No helper found for module: clock.,
[19.09.2021 13:04.18.383] [LOG]   Initializing new module helper ...,
[19.09.2021 13:04.18.383] [LOG]   Module helper loaded: MMM-CalendarWeek,
[19.09.2021 13:04.18.385] [ERROR] Whoops! There was an uncaught exception...,
[19.09.2021 13:04.18.388] [ERROR] Error: Cannot find module 'homeassistant',
Require stack:,
- /opt/magic_mirror/modules/MMM-HomeAssistant-Touch/node_helper.js,
- /opt/magic_mirror/js/app.js,
- /opt/magic_mirror/serveronly/index.js,
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15),
    at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29),
    at Function.Module._load (internal/modules/cjs/loader.js:667:27),
    at Module.require (internal/modules/cjs/loader.js:887:19),
    at require (internal/modules/cjs/helpers.js:74:18),
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-HomeAssistant-Touch/node_helper.js:2:23),
    at Module._compile (internal/modules/cjs/loader.js:999:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10),
    at Module.load (internal/modules/cjs/loader.js:863:32),
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {,
  code: 'MODULE_NOT_FOUND',,
  requireStack: [,
    '/opt/magic_mirror/modules/MMM-HomeAssistant-Touch/node_helper.js',,
    '/opt/magic_mirror/js/app.js',,
    '/opt/magic_mirror/serveronly/index.js',
  ],
},
[19.09.2021 13:04.18.388] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?,
[19.09.2021 13:04.18.389] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues,

```

It looks like i'm missing a module `[ERROR] Error: Cannot find module 'homeassistant'` but I'm lose as to which one it is.

Thanks

**Comment by mathewmeconry** [comment]
Hi @id-ic 
I guess you didn't run `npm install` or `yarn` inside the MMM-HomeAssistant-Touch folder, did you?
Because this error tells me that MagicMirror isn't able to find the module `homeasssistant` which is a dependency of MMM-HomeAsisstant-Touch

**Comment by id-ic** [comment]
I originally had not but i did yesterday and just ran it now. Pardon my lack of npm knowledge but does 'npm install' install dependencies?  I dont think i have that module loaded as my icons are still "Loading..."  Is it this module i need to install? https://github.com/zuo000/MMM-HomeAssistant

```
root@c7634160257c:/opt/magic_mirror/modules/MMM-HomeAssistant-Touch# npm install
npm WARN mmm-homeassistant-touch@1.0.0 No repository field.

audited 56 packages in 1.035s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by mathewmeconry** [comment]
Yes `npm install` does install the dependencies.
Nop it isn't.
Just cd into the directory of my module and run `npm install`. Then restart the MagicMirror and it should work.
If not please send me the logs again.

**Comment by id-ic** [comment]
I did do that before but i'm still getting the same. i just ran it again

```
root@c7634160257c:/opt/magic_mirror/modules/MMM-HomeAssistant-Touch# npm install
npm WARN mmm-homeassistant-touch@1.0.0 No repository field.

audited 56 packages in 0.93s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

root@c7634160257c:/opt/magic_mirror/modules/MMM-HomeAssistant-Touch# ls -l
total 72
-rw-r--r--  1 root root  2139 Sep 19 12:55 MMM-HomeAssistant-Touch.css
-rw-r--r--  1 root root  2801 Sep 19 12:55 MMM-HomeAssistant-Touch.js
-rw-r--r--  1 root root   821 Sep 19 12:55 Readme.md
drwxr-xr-x  2 root root  4096 Sep 19 12:55 UIClasses
drwxr-xr-x  2 root root  4096 Sep 19 12:55 helpers
-rw-r--r--  1 root root  5884 Sep 19 12:55 node_helper.js
drwxr-xr-x 59 root root  4096 Sep 19 22:09 node_modules
-rw-r--r--  1 root root 15548 Sep 19 12:55 package-lock.json
-rw-r--r--  1 root root   365 Sep 19 12:55 package.json
drwxr-xr-x  2 root root  4096 Sep 19 12:55 screenshots
-rw-r--r--  1 root root 15619 Sep 19 12:55 yarn.lock
root@c7634160257c:/opt/magic_mirror/modules/MMM-HomeAssistant-Touch# ls node_modules/
ajv          base64-js        dashdash        fast-deep-equal             har-validator     isomorphic-ws         jsprim           psl           sshpk         verror
asn1         bcrypt-pbkdf     delayed-stream  fast-json-stable-stringify  homeassistant     isstream              mime-db          punycode      tough-cookie  ws
assert-plus  buffer           ecc-jsbn        forever-agent               homeassistant-ws  jsbn                  mime-types       qs            tunnel-agent
asynckit     caseless         events          form-data                   http-signature    json-schema           moment           request       tweetnacl
aws-sign2    combined-stream  extend          getpass                     ieee754           json-schema-traverse  oauth-sign       safe-buffer   uri-js
aws4         core-util-is     extsprintf      har-schema                  is-typedarray     json-stringify-safe   performance-now  safer-buffer  uuid
root@c7634160257c:/opt/magic_mirror/modules/MMM-HomeAssistant-Touch# 

root@c7634160257c:/opt/magic_mirror/modules/MMM-HomeAssistant-Touch# ls -l node_modules/homeassistant
total 60
-rw-r--r-- 1 root root  1073 Oct 26  1985 LICENSE
-rw-r--r-- 1 root root  3440 Oct 26  1985 README.md
drwxr-xr-x 2 root root  4096 Sep 19 22:09 lib
-rw-r--r-- 1 root root  1623 Sep 19 22:09 package.json
drwxr-xr-x 2 root root  4096 Sep 19 22:09 test
-rw-r--r-- 1 root root 39325 Oct 26  1985 yarn.lock


```

**Comment by id-ic** [comment]
Well the error appeared to be PEBKAC.  Maybe i wasn't in the right directory when i did the `npm install`.  it's working now.  Thanks and great plug in!

**Comment by mathewmeconry** [comment]
Great :)
Glad to hear that ^^
If you miss any features don't hesitate to open an issue and request it
